name: JMeter Test

on:
  push:
    branches: [ main ]

jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run JMeter
      uses: public-transportation-tools/jmeter-action@v2.2
      with:
        script-file: ./scripts/reqres.jmx
        jmeter-version: 5.4.1
        jmeter-opts: "-Jthreads=10 -Jrampup=60 -Jduration=300,-JdataFile=./test-data/pages_data.csv"
